# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages

matrix:
  include:
  - env: 
      - PACKAGE_NAME=neuroconductor
      - dev=FALSE
      - deployment=FALSE
  - env: 
      - PACKAGE_NAME=neuroconductor-devel
      - dev=TRUE  
      - deployment=FALSE
  - env: 
      - PACKAGE_NAME=neuroconductor-devel-releases
      - dev=TRUE  
      - deployment=TRUE  
  - env: 
      - PACKAGE_NAME=oslerinhealth
      - dev=FALSE
      - deployment=FALSE
  # - env: 
  #     - PACKAGE_NAME=oslerinhealth-devel
  #     - dev=TRUE  
  #     - deployment=FALSE
  # - env: 
  #     - PACKAGE_NAME=oslerinhealth-releases
  #     - dev=TRUE  
  #     - deployment=TRUE        

script:
  - export error_opt="options(error=function() {q(status=1)}) "
  - neuro_user() {
      str="${error_opt}; neuroc.deps::neuroc_user(dev=${dev}, deployment=${deployment})";
      Rscript -e "${str}";
      if [[ "$?" != "0" ]]; then exit 1 ; fi ;
    }
  - use_neuroc_template() {
      str="${error_opt}; neuroc.deps::use_neuroc_template(dev=${dev}, deployment=${deployment})";
      Rscript -e "${str}";
      if [[ "$?" != "0" ]]; then exit 1 ; fi ;
    }
  - run_neuroc() {
      git clone https://github.com/${1} temp;
      cd temp ;
      use_neuroc_template ;
      if [[ "$?" != "0" ]]; then exit 1 ; fi ;      
      cat DESCRIPTION;
      echo "\n" ;
      cat .travis.yml ;
      cd ..; rm -rf temp ;
    }
  - run_neuroc muschellij2/gifti ;
  - run_neuroc muschellij2/neurobase ;
  - run_neuroc muschellij2/ANTsRCore ;
  - run_neuroc muschellij2/extrantsr ;

